const translations = {
    ru: {
        title: "Telegram - Социальная сеть и мессенджер",
        welcomeTitle: "Добро пожаловать в Telegram",
        welcomeText: "Связывайтесь с друзьями и семьей легко и быстро!",
        featuresTitle: "Почему выбирают нас?",
        secureMessagesTitle: "Безопасные сообщения",
        secureMessagesText: "Все ваши сообщения защищены сквозным шифрованием.",
        communitiesTitle: "Сообщества",
        communitiesText: "Создавайте сообщества по интересам и набирайте людей, объединенных общими увлечениями.",
        marketplaceTitle: "Маркетплейс",
        marketplaceText: "В нашем приложении есть маркет, где пользователи могут продавать свои товары и развивать бизнес.",
        cleanInterfaceTitle: "Чистый интерфейс",
        cleanInterfaceText: "В сети отсутствует любая реклама, что делает интерфейс очень приятным для использования.",
        downloadTitle: "Скачайте наше приложение",
        footerText: "&copy; 2024 Telegram. Все права защищены."
    },
    en: {
        title: "Telegram - Social Network and Messenger",
        welcomeTitle: "Welcome to Telegram",
        welcomeText: "Connect with friends and family easily and quickly!",
        featuresTitle: "Why Choose Us?",
        secureMessagesTitle: "Secure Messages",
        secureMessagesText: "All your messages are protected with end-to-end encryption.",
        communitiesTitle: "Communities",
        communitiesText: "Create communities based on interests and gather people with shared passions.",
        marketplaceTitle: "Marketplace",
        marketplaceText: "Our app features a marketplace where users can sell their goods and grow their business.",
        cleanInterfaceTitle: "Clean Interface",
        cleanInterfaceText: "The network is ad-free, making the interface very pleasant to use.",
        downloadTitle: "Download Our App",
        footerText: "&copy; 2024 Telegram. All rights reserved."
    },
    zh: {
        title: "Telegram - 社交网络和消息应用",
        welcomeTitle: "欢迎来到 Telegram",
        welcomeText: "轻松快速地与朋友和家人联系！",
        featuresTitle: "为什么选择我们？",
        secureMessagesTitle: "安全消息",
        secureMessagesText: "您的所有消息都受到端到端加密的保护。",
        communitiesTitle: "社区",
        communitiesText: "根据兴趣创建社区，聚集志同道合的人。",
        marketplaceTitle: "市场",
        marketplaceText: "我们的应用程序有一个市场，用户可以在这里出售商品并发展业务。",
        cleanInterfaceTitle: "干净的界面",
        cleanInterfaceText: "网络上没有任何广告，使界面非常愉快。",
        downloadTitle: "下载我们的应用",
        footerText: "&copy; 2024 Telegram. 保留所有权利。"
    },
    uk: {
        title: "Telegram - Соціальна мережа та месенджер",
        welcomeTitle: "Ласкаво просимо до Telegram",
        welcomeText: "Легко та швидко спілкуйтеся з друзями та родиною!",
        featuresTitle: "Чому обирають нас?",
        secureMessagesTitle: "Безпечні повідомлення",
        secureMessagesText: "Усі ваші повідомлення захищені наскрізним шифруванням.",
        communitiesTitle: "Спільноти",
        communitiesText: "Створюйте спільноти за інтересами та залучайте людей, об'єднаних спільними захопленнями.",
        marketplaceTitle: "Маркетплейс",
        marketplaceText: "У нашому додатку є маркет, де користувачі можуть продавати свої товари та розвивати бізнес.",
        cleanInterfaceTitle: "Чистий інтерфейс",
        cleanInterfaceText: "У мережі відсутня будь-яка реклама, що робить інтерфейс дуже приємним у використанні.",
        downloadTitle: "Скачайте наш додаток",
        footerText: "&copy; 2024 Telegram. Всі права захищені."
    },
    fr: {
        title: "Telegram - Réseau social et messager",
        welcomeTitle: "Bienvenue dans Telegram",
        welcomeText: "Connectez-vous facilement et rapidement avec vos amis et votre famille !",
        featuresTitle: "Pourquoi nous choisir ?",
                secureMessagesText: "Tous vos messages sont protégés par un chiffrement de bout en bout.",
        communitiesTitle: "Communautés",
        communitiesText: "Créez des communautés basées sur des intérêts et rassemblez des personnes partageant les mêmes passions.",
        marketplaceTitle: "Marché",
        marketplaceText: "Notre application dispose d'un marché où les utilisateurs peuvent vendre leurs biens et développer leur entreprise.",
        cleanInterfaceTitle: "Interface propre",
        cleanInterfaceText: "Le réseau est sans publicité, ce qui rend l'interface très agréable à utiliser.",
        downloadTitle: "Téléchargez notre application",
        footerText: "&copy; 2024 Telegram. Tous droits réservés."
    },
    ja: {
        title: "Telegram - ソーシャルネットワークとメッセンジャー",
        welcomeTitle: "Telegramへようこそ",
        welcomeText: "友達や家族と簡単に素早くつながりましょう！",
        featuresTitle: "なぜ私たちを選ぶのか？",
        secureMessagesTitle: "安全なメッセージ",
        secureMessagesText: "すべてのメッセージはエンドツーエンドの暗号化で保護されています。",
        communitiesTitle: "コミュニティ",
        communitiesText: "興味に基づいてコミュニティを作成し、共通の情熱を持つ人々を集めましょう。",
        marketplaceTitle: "マーケットプレイス",
        marketplaceText: "私たちのアプリには、ユーザーが商品を販売し、ビジネスを成長させるためのマーケットがあります。",
        cleanInterfaceTitle: "クリーンなインターフェース",
        cleanInterfaceText: "ネットワークには広告がなく、非常に快適に使用できます。",
        downloadTitle: "アプリをダウンロード",
        footerText: "&copy; 2024 Telegram. すべての権利を保留します。"
    },
    hi: {
        title: "Telegram - सोशल नेटवर्क और मैसेंजर",
        welcomeTitle: "Telegram में आपका स्वागत है",
        welcomeText: "दोस्तों और परिवार से आसानी से और जल्दी जुड़ें!",
        featuresTitle: "हमें क्यों चुनें?",
        secureMessagesTitle: "सुरक्षित संदेश",
        secureMessagesText: "आपके सभी संदेश एंड-टू-एंड एन्क्रिप्शन से सुरक्षित हैं।",
        communitiesTitle: "समुदाय",
        communitiesText: "रुचियों के आधार पर समुदाय बनाएं और समान जुनून वाले लोगों को इकट्ठा करें।",
        marketplaceTitle: "मार्केटप्लेस",
        marketplaceText: "हमारे ऐप में एक मार्केटप्लेस है जहां उपयोगकर्ता अपने सामान बेच सकते हैं और अपने व्यवसाय को बढ़ा सकते हैं।",
        cleanInterfaceTitle: "स्वच्छ इंटरफेस",
        cleanInterfaceText: "नेटवर्क में कोई विज्ञापन नहीं है, जिससे इंटरफेस का उपयोग करना बहुत सुखद है।",
        downloadTitle: "हमारा ऐप डाउनलोड करें",
        footerText: "&copy; 2024 Telegram. सर्वाधिकार सुरक्षित।"
    },
    id: {
        title: "Telegram - Jaringan Sosial dan Messenger",
        welcomeTitle: "Selamat datang di Telegram",
        welcomeText: "Sambungkan dengan teman dan keluarga dengan mudah dan cepat!",
        featuresTitle: "Mengapa Memilih Kami?",
        secureMessagesTitle: "Pesan Aman",
        secureMessagesText: "Semua pesan Anda dilindungi dengan enkripsi end-to-end.",
        communitiesTitle: "Komunitas",
        communitiesText: "Buat komunitas berdasarkan minat dan kumpulkan orang-orang dengan hasrat yang sama.",
        marketplaceTitle: "Pasar",
        marketplaceText: "Aplikasi kami memiliki pasar di mana pengguna dapat menjual barang mereka dan mengembangkan bisnis.",
        cleanInterfaceTitle: "Antarmuka Bersih",
        cleanInterfaceText: "Jaringan ini bebas iklan, membuat antarmuka sangat menyenangkan untuk digunakan.",
        downloadTitle: "Unduh Aplikasi Kami",
        footerText: "&copy; 2024 Telegram. Semua hak dilindungi."
    },
    ro: {
        title: "Telegram - Rețea socială și mesager",
        welcomeTitle: "Bine ați venit în Telegram",
        welcomeText: "Conectați-vă cu prietenii și familia cu ușurință și rapiditate!",
        featuresTitle: "De ce să ne alegeți?",
        secureMessagesTitle: "Mesaje Securizate",
        secureMessagesText: "Toate mesajele dvs. sunt protejate prin criptare end-to-end.",
        communitiesTitle: "Comunități",
        communitiesText: "Creați comunități bazate pe interese și adunați oameni cu pasiuni comune.",
        marketplaceTitle: "Piață",
        marketplaceText: "Aplicația noastră dispune de o piață unde utilizatorii pot vinde bunurile lor și își pot dezvolta afacerea.",
        cleanInterfaceTitle: "Interfață Curată",
        cleanInterfaceText: "Rețeaua este fără reclame, ceea ce face interfața foarte plăcută de utilizat.",
        downloadTitle: "Descărcați aplicația noastră",
        footerText: "&copy; 2024 Telegram. Toate drepturile rezervate."
    },
    pl: {
        title: "Telegram - Sieć społecznościowa i komunikator",
        welcomeTitle: "Witamy w Telegram",
        welcomeText: "Łatwo i szybko łącz się z przyjaciółmi i rodziną!",
        featuresTitle: "Dlaczego warto nas wybrać?",
        secureMessagesTitle: "Bezpieczne wiadomości",
        secureMessagesText: "Wszystkie Twoje wiadomości są chronione szyfrowaniem end-to-end.",
        communitiesTitle: "Społeczności",
        communitiesText: "Twórz społeczności oparte na zainteresowaniach i gromadź ludzi z podobnymi pasjami.",
        marketplaceTitle: "Rynek",
        marketplaceText: "Nasza aplikacja ma rynek, na którym użytkownicy mogą sprzedawać swoje towary i rozwijać biznes.",
        cleanInterfaceTitle: "Czysty interfejs",
        cleanInterfaceText: "Sieć jest wolna od reklam, co sprawia, że interfejs jest bardzo przyjemny w użyciu.",
        downloadTitle: "Pobierz naszą aplikację",
        footerText: "&copy; 2024 Telegram. Wszelkie prawa zastrzeżone."
    },
    ar: {
        title: "Telegram - شبكة اجتماعية ومرسل",
        welcomeTitle: "مرحبًا بك في Telegram",
        welcomeText: "تواصل مع الأصدقاء والعائلة بسهولة وسرعة!",
        featuresTitle: "لماذا تختارنا؟",
        secureMessagesTitle: "رسائل آمنة",
        secureMessagesText: "جميع رسائلك محمية بتشفير من طرف إلى طرف.",
        communitiesTitle: "مجتمعات",
        communitiesText: "أنشئ مجتمعات بناءً على الاهتمامات واجمع الأشخاص ذوي الشغف المشترك.",
        marketplaceTitle: "سوق",
        marketplaceText: "تحتوي تطبيقنا على سوق حيث يمكن للمستخدمين بيع سلعهم وتطوير أعمالهم.",
        cleanInterfaceTitle: "واجهة نظيفة",
        cleanInterfaceText: "الشبكة خالية من الإعلانات، مما يجعل الواجهة ممتعة جدًا للاستخدام.",
        downloadTitle: "قم بتنزيل تطبيقنا",
        footerText: "&copy; 2024 Telegram. جميع الحقوق محفوظة."
    },
    fa: {
        title: "Telegram - شبکه اجتماعی و پیام‌رسان",
        welcomeTitle: "به Telegram خوش آمدید",
        welcomeText: "به راحتی و سریع با دوستان و خانواده خود ارتباط برقرار کنید!",
        featuresTitle: "چرا ما را انتخاب کنید؟",
        secureMessagesTitle: "پیام‌های امن",
        secureMessagesText: "تمام پیام‌های شما با رمزنگاری انتها به انتها محافظت می‌شوند.",
        communitiesTitle: "جامعه‌ها",
        communitiesText: "بر اساس علایق جامعه بسازید و افرادی با اشتیاق‌های مشترک را جمع کنید.",
        marketplaceTitle: "بازار",
        marketplaceText: "برنامه ما دارای بازاری است که کاربران می‌توانند کالاهای خود را بفروشند و کسب‌وکار خود را توسعه دهند.",
        cleanInterfaceTitle: "رابط کاربری تمیز",
        cleanInterfaceText: "این شبکه بدون تبلیغات است و استفاده از آن بسیار لذت‌بخش است.",
        downloadTitle: "برنامه ما را دانلود کنید",
        footerText: "&copy; 2024 Telegram. تمامی حقوق محفوظ است."
    }
};

